import "../globals.css";
import theme from "../lib/theme";

import type { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "@mui/material/styles";
import Navbar from "../components/navbar/layout";
import Contact from "./(overview)/(contact)/page";

export const metadata: Metadata = {
  title: "Portifólio",
  description: "Generated by create Michelly Nonato",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { locale } = params;
  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider theme={theme}>
            <Navbar />
            <div className="flex flex-col gap-16">
              {children}
              <Contact />
            </div>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
